services:
  postgres:
    image: postgres:17
    container_name: local-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cavesdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:latest
    container_name: local-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  keycloak:
    image: quay.io/keycloak/keycloak:26.6.1
    container_name: local-keycloak
    restart: unless-stopped
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  pgdata: